METRIC_CRS = 3857
DEGREE_CRS = 4326

POPULATION_WEIGHT_COEFF = 1
FACTORY_SALARY_W_COEFF = 3
CITY_PARAMS_W_COEFF = 3
BAD_CLIMATE_W_COEFF = 3

MIN_FLOW_VALUE = 1

DISTANCE_TRASHOLD_METERS = (
    1e6 
)
DESTINATION_EXP_COEFF = 5
ORIGIN_EXP_COEFF = 1
DETERRENCE_FUNC_COEFF = -1